// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsWeqx-zcOUsBbDWQi0tu1fqkio4JY6sM',
    appId: '1:756573574933:web:23b374dae1e23401d1fb1c',
    messagingSenderId: '756573574933',
    projectId: 'loginapp-44dde',
    authDomain: 'loginapp-44dde.firebaseapp.com',
    storageBucket: 'loginapp-44dde.appspot.com',
    measurementId: 'G-Z3QL104RHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhhNfMYhPpKF2MK41MX3FX7drFyX8W3yU',
    appId: '1:756573574933:android:f6d031d0b5cd5ed3d1fb1c',
    messagingSenderId: '756573574933',
    projectId: 'loginapp-44dde',
    storageBucket: 'loginapp-44dde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSv9LFIIHtfHgHhVAm1gDMmVXvw5DXElQ',
    appId: '1:756573574933:ios:eb9d06914dc2b028d1fb1c',
    messagingSenderId: '756573574933',
    projectId: 'loginapp-44dde',
    storageBucket: 'loginapp-44dde.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );
}
